---
- hosts: lb
become: true
  roles:
    - { role: dragonbe.nginx_loadbalancer, when: enable_nginx_lb and load_balancer_is_required }
    - { role: apache, when: enable_apache_lb and load_balancer_is_required }

